CRUD.MVC/Controllers/EstabelecimentoController.cs
using System.Web.Mvc;
using AutoMapper;
using CRUD.Application.Interface;
using CRUD.Domain.Entities;
using CRUD.MVC.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace CRUD.MVC.Controllers
{
    public class EstabelecimentoController : Controller
    {
        // GET: Estabelecimento
        private readonly IEstabelecimentoAppService _estabelecimentoApp;
        private readonly ICategoriaAppService _categoriaApp;

        public EstabelecimentoController(IEstabelecimentoAppService estabelecimentoApp, ICategoriaAppService categoriaApp)
        {
            _estabelecimentoApp = estabelecimentoApp;
            _categoriaApp = categoriaApp;
        }

        // GET: Categoria
        public ActionResult Index()
        {
            var estabelecimentoViewModel = Mapper.Map<IEnumerable<Estabelecimento>, IEnumerable<EstabelecimentoViewModel>>(_estabelecimentoApp.GetAll());

            return View(estabelecimentoViewModel);
        }

        // GET: Categoria/Details/5
        public ActionResult Details(int id)
        {
            var estabelecimento = _estabelecimentoApp.GetById(id);
            var estabelecimentoViewModel = Mapper.Map<Estabelecimento, EstabelecimentoViewModel>(estabelecimento);

            return View(estabelecimentoViewModel);
        }

        // GET: Categoria/Create
        public ActionResult Create()
        {
            ViewBag.CategoriaId = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome");
            var model = new EstabelecimentoViewModel();
            return View(model);
        }

        // POST: Categoria/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EstabelecimentoViewModel estabelecimento)
        {
            var estabelecimentoDomain = Mapper.Map<EstabelecimentoViewModel, Estabelecimento>(estabelecimento);
            var categoriaVinculada = _categoriaApp.ObterCategoria(estabelecimento.CategoriaId);
            
            estabelecimentoDomain.VinculaCategoria(categoriaVinculada);
            estabelecimento.Result = estabelecimentoDomain.Validate();
            
            if (estabelecimento.Result.Count() == 0)
            {
                _estabelecimentoApp.Add(estabelecimentoDomain);
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaId = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", estabelecimento.CategoriaId);

            return View(estabelecimento);
        }

        // GET: Categoria/Edit/5
        public ActionResult Edit(int id)
        {
            var estabelecimento = _estabelecimentoApp.GetById(id);
            var estabelecimentoViewModel = Mapper.Map<Estabelecimento, EstabelecimentoViewModel>(estabelecimento);

            ViewBag.CategoriaId = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", estabelecimentoViewModel.CategoriaId);

            return View(estabelecimentoViewModel);
        }

        // POST: Categoria/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EstabelecimentoViewModel estabelecimento)
        {
            if (ModelState.IsValid)
            {
                var estabelecimentoDomain = Mapper.Map<EstabelecimentoViewModel, Estabelecimento>(estabelecimento);
                _estabelecimentoApp.Update(estabelecimentoDomain);

                return RedirectToAction("Index");
            }

            ViewBag.CategoriaId = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", estabelecimento.CategoriaId);
            return View(estabelecimento);
        }

        // GET: Categoria/Delete/5
        public ActionResult Delete(int id)
        {
            var estabelecimento = _estabelecimentoApp.GetById(id);
            var estabelecimentoViewModel = Mapper.Map<Estabelecimento, EstabelecimentoViewModel>(estabelecimento);

            return View(estabelecimentoViewModel);
        }

        // POST: Categoria/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var estabelecimento = _estabelecimentoApp.GetById(id);
            _estabelecimentoApp.Remove(estabelecimento);

            return RedirectToAction("Index");
        }
    }
}

CRUD.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CRUD.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CRUD.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CRUD.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Cadastro de Estabelecimentos</h1>
    <p class="lead">Lorem ipsum dolor sit a met.</p>
    <p><a>@Html.ActionLink("Cadastrar", "Index", "Estabelecimento")</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>